const treeData = [
    {
        id: 1,
        parent_id: null,
        type: 'folder',
        name: 'Folder 1',
        folder_data: [],
    },
    {
        id: 2,
        parent_id: null,
        type: 'folder',
        name: 'Совершенно новая папка с длинным названием',
        folder_data: [
            {
                id: 3,
                parent_id: 2,
                nested: 1,
                type: 'file',
                name: 'File 1',
                text: '# Hello world!',
            },
            {
                id: 4,
                parent_id: 2,
                nested: 1,
                type: 'file',
                name: 'File 2',
                text: 'Whats a *beautiful* article!',
            },
        ],
    },
    {
        id: 5,
        parent_id: null,
        type: 'folder',
        name: 'Folder 3',
        folder_data: [
            {
                id: 6,
                parent_id: 5,
                nested: 1,
                type: 'file',
                name: 'File 1',
                text: '# File number one!',
            },
            {
                id: 7,
                parent_id: 5,
                nested: 1,
                type: 'file',
                name: 'File 2',
                text: '# And file number two!',
            },
        ],
    },
    {
        id: 11,
        parent_id: null,
        type: 'file',
        name: 'File 1',
        text: '',
    },
    {
        id: 12,
        parent_id: null,
        type: 'file',
        name: 'File 2',
        text: 'Some text here.',
    },
    {
        id: 13,
        parent_id: null,
        type: 'file',
        name: 'File 3',
        text: '',
    },
    {
        id: 14,
        parent_id: null,
        type: 'folder',
        name: 'Folder 3',
        folder_data: [
            {
                id: 15,
                parent_id: 5,
                nested: 1,
                type: 'file',
                name: 'File 1',
                text: 'File number one!',
            },
            {
                id: 16,
                parent_id: 5,
                nested: 1,
                type: 'file',
                name: 'File 2',
                text: 'And file number two!',
            },
        ],
    },
    {
        id: 17,
        parent_id: null,
        type: 'folder',
        name: 'Folder 3',
        folder_data: [
            {
                id: 18,
                parent_id: 5,
                nested: 1,
                type: 'file',
                name: 'File 1',
                text: 'File number one!',
            },
            {
                id: 19,
                parent_id: 5,
                nested: 1,
                type: 'file',
                name: 'File 2',
                text: 'And file number two!',
            },
        ],
    },
];